//
//  ContentView.swift
//  campfiresongs
//
//  Created by Joseph Griffin on 26.05.24.
//

import SwiftUI

enum Song: String, CaseIterable {
    case selectasong = "Select a song"
    case mematen = "Me Maten - C Tangana"
    case isthislove = "Is This Love - Bob Marley"
    case labamba = "La Bamba - Ritchie Valens"
    case countryroads = "Country Roads - John Denver"
    case whiskeyinthejar = "Whiskey in the Jar - The Dubliners"
    case tellmema = "I'll Tell Me Ma - The Irish Rovers"
    case macarena = "Macarena - Los del Río"
}

struct ContentView: View {
    @State var selectedSong: Song = .selectasong
    
    var body: some View {
        ScrollView{
            VStack {
                Text("Campfire Songs")
                    .font(.system(size: 50))
                Text("⛺️🔥🎵")
                    .font(.system(size: 40))
                Picker("Select song", selection: $selectedSong) {
                    ForEach(Song.allCases, id: \.self) {
                        song in Text(song.rawValue)
                    }
//                    .font(.system(size: 10))
                }
                Spacer()
//                Text(selectedSong.rawValue)
//                    .font(.system(size: 30))
//                    .multilineTextAlignment(.center)
//                Text("  ")
                SongLyrics(selectedSong: selectedSong)
                    .font(.system(size: 20))
                    .multilineTextAlignment(.center)
                Spacer()
            }
//            .navigationTitle("Campfire Songs 🎵")
            .padding()
        }
    }
}

struct SongLyrics: View {
    var selectedSong: Song
    
    var body: some View {
        switch selectedSong {
        case .selectasong:
            Text("")
        case .isthislove:
            Text("I wanna love you")
            Text("and treat you right")
            Text("I wanna love you")
            Text("every day and every night")
            Text("We'll be together")
            Text("with a roof right over our heads")
            Text("We'll share the shelter")
            Text("of my single bed")
            Text("We'll share the same room, yeah")
            Text("for Jah provide the bread")
            Text("")
            Text("")
            Text("Is this love? Is this love? Is this love?")
            Text("Is this love that I'm feeling?")
            Text("Is this love? Is this love? Is this love?")
            Text("Is this love that I'm feeling?")
            Text("I wanna know, wanna know, wanna know now")
            Text("I got to know, got to know, got to know now")
            Text("I-I-I-I-I-I-I-I-I, I'm willing and able")
            Text("So I throw my cards on your table")
            Text("")
            Text("")
            Text("I wanna love you, I wanna love and treat")
            Text("Love and treat you right")
            Text("I wanna love you")
            Text("every day and every night")
            Text("We'll be together")
            Text("with a roof right over our heads")
            Text("We'll share the shelter")
            Text("of my single bed")
            Text("We'll share the same room, yeah")
            Text("for Jah provide the bread")
            Text("")
            Text("")
            Text("Is this love? Is this love? Is this love?")
            Text("Is this love that I'm feeling?")
            Text("Is this love? Is this love? Is this love?")
            Text("Is this love that I'm feeling?")
            Text("Wo-o-o-oah")
            Text("Oh, yes, I know, yes, I know, yes, I know now")
            Text("Oh, yes, I know, yes, I know, yes, I know now")
            Text("I-I-I-I-I-I-I-I-I, I'm willing and able")
            Text("So I throw my cards on your table")
            Text("")
            Text("")
            Text("See, I wanna love you, I wanna love and treat you")
            Text("Love and treat you right")
            Text("I wanna love you")
            Text("every day and every night")
            Text("We'll be together")
            Text("with a roof right over our heads")
            Text("We'll share the shelter")
            Text("of my single bed")
            Text("We'll share the same room, yeah")
            Text("for Jah provide the bread")
            
        case .labamba:
            Text("Para bailar La Bamba")
            Text("Para bailar La Bamba")
            Text("Se necesita una poca de gracia")
            Text("una poca de gracia")
            Text("Pa' mí, pa' ti, ay arriba, ay arriba")
            Text("Y arriba, y arriba")
            Text("Por ti seré, por ti seré, por ti seré")
            Text("")
            Text("")
            Text("Yo no soy marinero")
            Text("Yo no soy marinero, soy capitán")
            Text("Soy capitán, soy capitán")
            Text("")
            Text("")
            Text("Bamba, bamba")
            Text("Bamba, bamba")
            Text("Bamba, bamba")
            Text("")
            Text("")
            Text("Para bailar La Bamba")
            Text("Para bailar La Bamba")
            Text("Se necesita una poca de gracia")
            Text("una poca de gracia")
            Text("Pa' mí, pa' ti, ay arriba, ay arriba")
            Text("")
            Text("")
            Text("Para bailar La Bamba")
            Text("Para bailar La Bamba")
            Text("Se necesita una poca de gracia")
            Text("una poca de gracia")
            Text("Pa' mí, pa' ti, ay arriba, ay arriba")
            Text("Y arriba, y arriba")
            Text("Por ti seré, por ti seré, por ti seré")
            Text("")
            Text("")
            Text("Bamba, bamba")
            Text("Bamba, bamba")
            Text("Bamba, bamba")
            Text("Bamba, bamba")
            
        case .countryroads:
            Text("Almost heaven, West Virginia")
            Text("Blue Ridge Mountains, Shenandoah River")
            Text("Life is old there, older than the trees")
            Text("Younger than the mountains, growin' like a breeze")
            Text("")
            Text("")
            Text("Country roads, take me home")
            Text("To the place I belong")
            Text("West Virginia, mountain mama")
            Text("Take me home, country roads")
            Text("")
            Text("")
            Text("All my memories gather 'round her")
            Text("Miner's lady, stranger to blue water")
            Text("Dark and dusty, painted on the sky")
            Text("Misty taste of moonshine, teardrop in my eye")
            Text("")
            Text("")
            Text("Country roads, take me home")
            Text("To the place I belong")
            Text("West Virginia, mountain mama")
            Text("Take me home, country roads")
            Text("")
            Text("")
            Text("I hear her voice in the mornin' hour, she calls me")
            Text("The radio reminds me of my home far away")
            Text("Drivin' down the road, I get a feelin'")
            Text("That I should've been home yesterday, yesterday")
            Text("")
            Text("")
            Text("Country roads, take me home")
            Text("To the place I belong")
            Text("West Virginia, mountain mama")
            Text("Take me home, country roads")
            Text("")
            Text("")
            Text("Country roads, take me home")
            Text("To the place I belong")
            Text("West Virginia, mountain mama")
            Text("Take me home, country roads")
            Text("")
            Text("")
            Text("Take me home, country roads")
            Text("Take me home, country roads")
            
        case .mematen:
            Text("Me-Me ma—, me maten")
            Text("Me-Me ma—, me maten")
            Text("Me-Me ma—, me maten")
            Text("Me-Me ma—, me maten")
            Text("")
            Text("")
            Text("Me-Me ma—, me maten")
            Text("Me-Me ma—, me maten")
            Text("Me-Me ma—, me maten")
            Text("Me-Me ma—")
            Text("")
            Text("")
            Text("Las cosas que mi gente quiere")
            Text("Son las cosas que siempre hе querido")
            Text("Una copita pa' brindar y otras dos pa' los dos que viеnen contigo")
            Text("Los que no me subían a internet vacilando de amigo")
            Text("Ahora que nos ponen la alfombrita roja vienen conmigo")
            Text("")
            Text("")
            Text("Me maten si no pueden entrar")
            Text("Me muera, no les puedo fallar")
            Text("Yo sin esta gente, ¿pa' qué cojones quiero pasar?")
            Text("")
            Text("")
            Text("Me maten si no pueden entrar")
            Text("Me muera, no les puedo fallar")
            Text("Yo sin esta gente, ¿pa' qué cojones quiero pasar?")
            Text("")
            Text("")
            Text("Me-Me ma—, me maten")
            Text("Me-Me ma—, me maten")
            Text("Me-Me ma—, me maten")
            Text("Me-Me ma—, me maten")
            Text("")
            Text("")
            Text("Me-Me ma—, me maten")
            Text("Me-Me ma—, me maten")
            Text("Me-Me ma—, me maten")
            Text("Me-Me ma—")
            Text("")
            Text("")
            Text("En la vida nos pensamos que la gloria es el dinero")
            Text("Pero, pero nos equivocamos, nuestra gente es lo primero")
            Text("")
            Text("")
            Text("Y el pibe de la puerta dice que somos muchos")
            Text("Hemos vení'o como seis Carmona y seis más con Pucho")
            Text("")
            Text("")
            Text("Y el pibe de la puerta dice que somos muchos")
            Text("Hemos vení'o como seis Carmona y seis más con Pucho")
            Text("")
            Text("")
            Text("Me maten si no pueden entrar")
            Text("Me muera, no les puedo fallar")
            Text("Yo sin esta gente, ¿pa' qué cojones quiero pasar?")
            Text("")
            Text("")
            Text("Me maten si no pueden entrar")
            Text("Me muera, no les puedo fallar")
            Text("Yo sin esta gente, ¿pa' qué cojones quiero pasar?")
            Text("")
            Text("")
            Text("Me-Me ma—, me maten")
            Text("Me-Me ma—, me maten")
            Text("Me-Me ma—, me maten")
            Text("Me-Me ma—, me maten")
            Text("")
            Text("")
            Text("Me-Me ma—, me maten")
            Text("Me-Me ma—, me maten")
            Text("Me-Me ma—, me maten")
            Text("Me-Me ma, me maten!")
            
            
        case .whiskeyinthejar:
            Text("As I was a goin′ over the far famed Kerry mountains")
            Text("I met with captain Farrell and his money he was counting")
            Text("I first produced me pistol and I then produced me rapier")
            Text("Saying 'Stand and deliver' for he were a bold deceiver")
            Text("")
            Text("")
            Text("Mush-a ring dum-a do dum-a da")
            Text("Whack for me daddy-o")
            Text("Whack for me daddy-o")
            Text("There's whiskey in the jar")
            Text("")
            Text("")
            Text("I counted out his money and it made a pretty penny")
            Text("I put it in me pocket and I took it home to Jenny")
            Text("She sighed and she swore that she never would deceive me")
            Text("But the devil take the women for they never can be easy")
            Text("")
            Text("")
            Text("Mush-a ring dum-a do dum-a da")
            Text("Whack for me daddy-o")
            Text("Whack for me daddy-o")
            Text("There's whiskey in the jar")
            Text("")
            Text("")
            Text("I went up to me chamber, all for to take a slumber")
            Text("I dreamt of gold and jewels and for sure 't was no wonder")
            Text("But Jenny drew me charges and she filled them up with water")
            Text("Then sent for captain Farrell to be ready for the slaughter")
            Text("")
            Text("")
            Text("Mush-a ring dum-a do dum-a da")
            Text("Whack for me daddy-o")
            Text("Whack for me daddy-o")
            Text("There's whiskey in the jar")
            Text("")
            Text("")
            Text("′Twas was early in the morning, just before I rose to travel")
            Text("Up comes a band of footmen and likewise captain Farrell")
            Text("I first produced me pistol for she stole away me rapier")
            Text("I couldn′t shoot the water, so a prisoner I was taken")
            Text("")
            Text("")
            Text("Mush-a ring dum-a do dum-a da")
            Text("Whack for me daddy-o")
            Text("Whack for me daddy-o")
            Text("There's whiskey in the jar")
            Text("")
            Text("")
            Text("Now there′s some take delight in the carriages a-rollin'")
            Text("And others take delight in the hurling and the bowling")
            Text("But I take delight in the juice of the barley")
            Text("And courting pretty fair maids in the morning bright and early")
            Text("")
            Text("")
            Text("Mush-a ring dum-a do dum-a da")
            Text("Whack for me daddy-o")
            Text("Whack for me daddy-o")
            Text("There's whiskey in the jar")
            Text("")
            Text("")
            Text("If anyone can aid me 'tis me brother in the army")
            Text("If I can find his station in Cork or in Killarney")
            Text("And if he′ll go with me, we'll go rovin' through Killkenny")
            Text("And I′m sure he′ll treat me better than me own a-sporting Jenny")
            Text("")
            Text("")
            Text("Mush-a ring dum-a do dum-a da")
            Text("Whack for me daddy-o")
            Text("Whack for me daddy-o")
            Text("There's whiskey in the jar")
            Text("")
            Text("")
            Text("Mush-a ring dum-a do dum-a da")
            Text("Whack for me daddy-o")
            Text("Whack for me daddy-o")
            Text("There's whiskey in the jar")

            
        case .tellmema:
            Text("I'll tell me ma when I get home")
            Text("The boys won't leave the girls alone")
            Text("Pulled me hair, stole me comb")
            Text("But that's alright till I go home")
            Text("")
            Text("")
            Text("She is handsome, she is pretty")
            Text("She is the belle of Dublin city")
            Text("She is a-courting, a-one, two, three")
            Text("Pray, can you tell me who is she?")
            Text("")
            Text("")
            Text("Albert Mooney says he loves her")
            Text("All the boys are fightin' for her")
            Text("Knock at the door, they ring on the bell")
            Text("Hello, me true love, are you well?")
            Text("")
            Text("")
            Text("Out she comes, white as snow")
            Text("Rings on her fingers, bells on her toes")
            Text("Ol' Jenny Morrissey says she'll die")
            Text("If she doesn't get the fella with the rovin' eye")
            Text("")
            Text("")
            Text("I'll tell me ma when I get home")
            Text("The boys won't leave the girls alone")
            Text("Pulled me hair, stole me comb")
            Text("But that's alright till I go home")
            Text("")
            Text("")
            Text("She is handsome, she is pretty")
            Text("She is the belle of Dublin city")
            Text("She is a-courting, a-one, two, three")
            Text("Pray, can you tell me who is she?")
            Text("")
            Text("")
            Text("Let the wind and the rain and the hail blow high")
            Text("And the snow come travelling through the sky")
            Text("She's as sweet as apple pie")
            Text("She'll get her own lad by and by")
            Text("")
            Text("")
            Text("When she gets a lad of her own")
            Text("She won't tell her ma when she gets home")
            Text("Let them all come as they will")
            Text("It's Albert Mooney she loves still")
            Text("")
            Text("")
            Text("I'll tell me ma when I get home")
            Text("The boys won't leave the girls alone")
            Text("Pulled me hair, stole me comb")
            Text("But that's alright till I go home")
            Text("")
            Text("")
            Text("She is handsome, she is pretty")
            Text("She is the belle of Dublin city")
            Text("She is a-courting, a-one, two, three")
            Text("Pray, can you tell me who is she?")

            
        case .macarena:
            Text("Dale a tu cuerpo alegría Macarena")
            Text("Que tu cuerpo es pa' darle alegría y cosa buena")
            Text("Dale a tu cuerpo alegría, Macarena")
            Text("Hey Macarena, ay")
            Text("")
            Text("")
            Text("Dale a tu cuerpo alegría Macarena")
            Text("Que tu cuerpo es pa' darle alegría y cosa buena")
            Text("Dale a tu cuerpo alegría, Macarena")
            Text("Hey Macarena, ay")
            Text("")
            Text("")
            Text("Macarena tiene un novio que se llama")
            Text("Que se llama de apellido Vitorino")
            Text("Y en la jura de bandera del muchacho")
            Text("Se la dio con dos amigos, ay")
            Text("")
            Text("")
            Text("Macarena tiene un novio que se llama")
            Text("Que se llama de apellido Vitorino")
            Text("Y en la jura de bandera del muchacho")
            Text("Se la dio con dos amigos, ay")
            Text("")
            Text("")
            Text("Dale a tu cuerpo alegría Macarena")
            Text("Que tu cuerpo es pa' darle alegría y cosa buena")
            Text("Dale a tu cuerpo alegría, Macarena")
            Text("Hey Macarena, ay")
            Text("")
            Text("")
            Text("Dale a tu cuerpo alegría Macarena")
            Text("Que tu cuerpo es pa' darle alegría y cosa buena")
            Text("Dale a tu cuerpo alegría, Macarena")
            Text("Hey Macarena, ay")
            Text("")
            Text("")
            Text("Macarena, Macarena, Macarena")
            Text("Que te gustan los veranos de Marbella")
            Text("Macarena, Macarena, Macarena")
            Text("Que te gusta la movida guerrillera, ay")
            Text("")
            Text("")
            Text("Dale a tu cuerpo alegría Macarena")
            Text("Que tu cuerpo es pa' darle alegría y cosa buena")
            Text("Dale a tu cuerpo alegría, Macarena")
            Text("Hey Macarena, ay")
            Text("")
            Text("")
            Text("Dale a tu cuerpo alegría Macarena")
            Text("Que tu cuerpo es pa' darle alegría y cosa buena")
            Text("Dale a tu cuerpo alegría, Macarena")
            Text("Hey Macarena, ay")
            Text("")
            Text("")
            Text("Macarena sueña con el corte inglés")
            Text("Y se compra los modelos más modernos")
            Text("Le gustaría vivir en Nueva York")
            Text("Y ligar un novio nuevo, ay")
            Text("")
            Text("")
            Text("Macarena sueña con el corte inglés")
            Text("Y se compra los modelos más modernos")
            Text("Le gustaría vivir en Nueva York")
            Text("Y ligar un novio nuevo, ay")
            Text("")
            Text("")
            Text("Dale a tu cuerpo alegría Macarena")
            Text("Que tu cuerpo es pa' darle alegría y cosa buena")
            Text("Dale a tu cuerpo alegría, Macarena")
            Text("Hey Macarena, ay")
            Text("")
            Text("")
            Text("Dale a tu cuerpo alegría Macarena")
            Text("Que tu cuerpo es pa' darle alegría y cosa buena")
            Text("Dale a tu cuerpo alegría, Macarena")
            Text("Hey Macarena, ay")
            
            
        }
    }
}

#Preview {
    ContentView()
}
