//
//  ContentView.swift
//  campfiresongs
//
//  Created by Joseph Griffin on 26.05.24.
//

import SwiftUI

enum Song: String, CaseIterable {
    case selectasong = "Select a song"
    case couldyoubeloved = "Could You Be Loved - Bob Marley"
    case isthislove = "Is This Love - Bob Marley"
    case labamba = "La Bamba - Ritchie Valens"
    case countryroads = "Country Roads - John Denver"
    case whiskeyinthejar = "Whiskey in the Jar - The Dubliners"
    case tellmema = "I'll Tell Me Ma - The Irish Rovers"
    case macarena = "Macarena - Los del Río"
}

struct ContentView: View {
    @State var selectedSong: Song = .selectasong
    
    var body: some View {
        ScrollView{
            VStack {
                Text("Campfire Songs")
                    .font(.system(size: 50))
                Text("⛺️🔥🎵")
                    .font(.system(size: 40))
                Picker("Select song", selection: $selectedSong) {
                    ForEach(Song.allCases, id: \.self) {
                        song in Text(song.rawValue)
                    }
//                    .font(.system(size: 10))
                }
                Spacer()
//                Text(selectedSong.rawValue)
//                    .font(.system(size: 30))
//                    .multilineTextAlignment(.center)
//                Text("  ")
                SongLyrics(selectedSong: selectedSong)
                    .font(.system(size: 20))
                    .multilineTextAlignment(.center)
                Spacer()
            }
//            .navigationTitle("Campfire Songs 🎵")
            .padding()
        }
    }
}

struct SongLyrics: View {
    var selectedSong: Song
    
    var body: some View {
        switch selectedSong {
        case .selectasong:
            Text("")
        case .isthislove:
            Text("I wanna love you")
            Text("and treat you right")
            Text("I wanna love you")
            Text("every day and every night")
            Text("We'll be together")
            Text("with a roof right over our heads")
            Text("We'll share the shelter")
            Text("of my single bed")
            Text("We'll share the same room, yeah")
            Text("for Jah provide the bread")
            Text("")
            Text("")
            Text("Is this love? Is this love? Is this love?")
            Text("Is this love that I'm feeling?")
            Text("Is this love? Is this love? Is this love?")
            Text("Is this love that I'm feeling?")
            Text("I wanna know, wanna know, wanna know now")
            Text("I got to know, got to know, got to know now")
            Text("I-I-I-I-I-I-I-I-I, I'm willing and able")
            Text("So I throw my cards on your table")
            Text("")
            Text("")
            Text("I wanna love you, I wanna love and treat")
            Text("Love and treat you right")
            Text("I wanna love you")
            Text("every day and every night")
            Text("We'll be together")
            Text("with a roof right over our heads")
            Text("We'll share the shelter")
            Text("of my single bed")
            Text("We'll share the same room, yeah")
            Text("for Jah provide the bread")
            Text("")
            Text("")
            Text("Is this love? Is this love? Is this love?")
            Text("Is this love that I'm feeling?")
            Text("Is this love? Is this love? Is this love?")
            Text("Is this love that I'm feeling?")
            Text("Wo-o-o-oah")
            Text("Oh, yes, I know, yes, I know, yes, I know now")
            Text("Oh, yes, I know, yes, I know, yes, I know now")
            Text("I-I-I-I-I-I-I-I-I, I'm willing and able")
            Text("So I throw my cards on your table")
            Text("")
            Text("")
            Text("See, I wanna love you, I wanna love and treat you")
            Text("Love and treat you right")
            Text("I wanna love you")
            Text("every day and every night")
            Text("We'll be together")
            Text("with a roof right over our heads")
            Text("We'll share the shelter")
            Text("of my single bed")
            Text("We'll share the same room, yeah")
            Text("for Jah provide the bread")
            
        case .labamba:
            Text("Para bailar La Bamba")
            Text("Para bailar La Bamba")
            Text("Se necesita una poca de gracia")
            Text("una poca de gracia")
            Text("Pa' mí, pa' ti, ay arriba, ay arriba")
            Text("Y arriba, y arriba")
            Text("Por ti seré, por ti seré, por ti seré")
            Text("")
            Text("")
            Text("Yo no soy marinero")
            Text("Yo no soy marinero, soy capitán")
            Text("Soy capitán, soy capitán")
            Text("")
            Text("")
            Text("Bamba, bamba")
            Text("Bamba, bamba")
            Text("Bamba, bamba")
            Text("")
            Text("")
            Text("Para bailar La Bamba")
            Text("Para bailar La Bamba")
            Text("Se necesita una poca de gracia")
            Text("una poca de gracia")
            Text("Pa' mí, pa' ti, ay arriba, ay arriba")
            Text("")
            Text("")
            Text("Para bailar La Bamba")
            Text("Para bailar La Bamba")
            Text("Se necesita una poca de gracia")
            Text("una poca de gracia")
            Text("Pa' mí, pa' ti, ay arriba, ay arriba")
            Text("Y arriba, y arriba")
            Text("Por ti seré, por ti seré, por ti seré")
            Text("")
            Text("")
            Text("Bamba, bamba")
            Text("Bamba, bamba")
            Text("Bamba, bamba")
            Text("Bamba, bamba")
            
        case .countryroads:
            Text("Almost heaven, West Virginia")
            Text("Blue Ridge Mountains, Shenandoah River")
            Text("Life is old there, older than the trees")
            Text("Younger than the mountains, growin' like a breeze")
            Text("")
            Text("")
            Text("Country roads, take me home")
            Text("To the place I belong")
            Text("West Virginia, mountain mama")
            Text("Take me home, country roads")
            Text("")
            Text("")
            Text("All my memories gather 'round her")
            Text("Miner's lady, stranger to blue water")
            Text("Dark and dusty, painted on the sky")
            Text("Misty taste of moonshine, teardrop in my eye")
            Text("")
            Text("")
            Text("Country roads, take me home")
            Text("To the place I belong")
            Text("West Virginia, mountain mama")
            Text("Take me home, country roads")
            Text("")
            Text("")
            Text("I hear her voice in the mornin' hour, she calls me")
            Text("The radio reminds me of my home far away")
            Text("Drivin' down the road, I get a feelin'")
            Text("That I should've been home yesterday, yesterday")
            Text("")
            Text("")
            Text("Country roads, take me home")
            Text("To the place I belong")
            Text("West Virginia, mountain mama")
            Text("Take me home, country roads")
            Text("")
            Text("")
            Text("Country roads, take me home")
            Text("To the place I belong")
            Text("West Virginia, mountain mama")
            Text("Take me home, country roads")
            Text("")
            Text("")
            Text("Take me home, country roads")
            Text("Take me home, country roads")
            
        case .couldyoubeloved:
            Text("lyrics to come")
            Text("")
            Text("")
            Text("")
            Text("")
            Text("")
            Text("")
            Text("")
            Text("")

            
        case .whiskeyinthejar:
            Text("lyrics to come")
            Text("")
            Text("")
            Text("")
            Text("")
            Text("")
            Text("")
            Text("")
            Text("")
            Text("")
            Text("")
            Text("")
            Text("")
            Text("")
            Text("")
            Text("")
            Text("")
            Text("")
            Text("")
            Text("")
            Text("")
            
        case .tellmema:
            Text("I'll tell me ma when I get home")
            Text("The boys won't leave the girls alone")
            Text("Pulled me hair, stole me comb")
            Text("But that's alright till I go home")
            Text("")
            Text("")
            Text("She is handsome, she is pretty")
            Text("She is the belle of Dublin city")
            Text("She is a-courting, a-one, two, three")
            Text("Pray, can you tell me who is she?")
            Text("")
            Text("")
            Text("Albert Mooney says he loves her")
            Text("All the boys are fightin' for her")
            Text("Knock at the door, they ring on the bell")
            Text("Hello, me true love, are you well?")
            Text("")
            Text("")
            Text("Out she comes, white as snow")
            Text("Rings on her fingers, bells on her toes")
            Text("Ol' Jenny Morrissey says she'll die")
            Text("If she doesn't get the fella with the rovin' eye")
            Text("")
            Text("")
            Text("I'll tell me ma when I get home")
            Text("The boys won't leave the girls alone")
            Text("Pulled me hair, stole me comb")
            Text("But that's alright till I go home")
            Text("")
            Text("")
            Text("She is handsome, she is pretty")
            Text("She is the belle of Dublin city")
            Text("She is a-courting, a-one, two, three")
            Text("Pray, can you tell me who is she?")
            Text("")
            Text("")
            Text("Let the wind and the rain and the hail blow high")
            Text("And the snow come travelling through the sky")
            Text("She's as sweet as apple pie")
            Text("She'll get her own lad by and by")
            Text("")
            Text("")
            Text("When she gets a lad of her own")
            Text("She won't tell her ma when she gets home")
            Text("Let them all come as they will")
            Text("It's Albert Mooney she loves still")
            Text("")
            Text("")
            Text("I'll tell me ma when I get home")
            Text("The boys won't leave the girls alone")
            Text("Pulled me hair, stole me comb")
            Text("But that's alright till I go home")
            Text("")
            Text("")
            Text("She is handsome, she is pretty")
            Text("She is the belle of Dublin city")
            Text("She is a-courting, a-one, two, three")
            Text("Pray, can you tell me who is she?")

            
        case .macarena:
            Text("Dale a tu cuerpo alegría Macarena")
            Text("Que tu cuerpo es pa' darle alegría y cosa buena")
            Text("Dale a tu cuerpo alegría, Macarena")
            Text("Hey Macarena, ay")
            Text("")
            Text("")
            Text("Dale a tu cuerpo alegría Macarena")
            Text("Que tu cuerpo es pa' darle alegría y cosa buena")
            Text("Dale a tu cuerpo alegría, Macarena")
            Text("Hey Macarena, ay")
            Text("")
            Text("")
            Text("Macarena tiene un novio que se llama")
            Text("Que se llama de apellido Vitorino")
            Text("Y en la jura de bandera del muchacho")
            Text("Se la dio con dos amigos, ay")
            Text("")
            Text("")
            Text("Macarena tiene un novio que se llama")
            Text("Que se llama de apellido Vitorino")
            Text("Y en la jura de bandera del muchacho")
            Text("Se la dio con dos amigos, ay")
            Text("")
            Text("")
            Text("Dale a tu cuerpo alegría Macarena")
            Text("Que tu cuerpo es pa' darle alegría y cosa buena")
            Text("Dale a tu cuerpo alegría, Macarena")
            Text("Hey Macarena, ay")
            Text("")
            Text("")
            Text("Dale a tu cuerpo alegría Macarena")
            Text("Que tu cuerpo es pa' darle alegría y cosa buena")
            Text("Dale a tu cuerpo alegría, Macarena")
            Text("Hey Macarena, ay")
            Text("")
            Text("")
            Text("Macarena, Macarena, Macarena")
            Text("Que te gustan los veranos de Marbella")
            Text("Macarena, Macarena, Macarena")
            Text("Que te gusta la movida guerrillera, ay")
            Text("")
            Text("")
            Text("Dale a tu cuerpo alegría Macarena")
            Text("Que tu cuerpo es pa' darle alegría y cosa buena")
            Text("Dale a tu cuerpo alegría, Macarena")
            Text("Hey Macarena, ay")
            Text("")
            Text("")
            Text("Dale a tu cuerpo alegría Macarena")
            Text("Que tu cuerpo es pa' darle alegría y cosa buena")
            Text("Dale a tu cuerpo alegría, Macarena")
            Text("Hey Macarena, ay")
            Text("")
            Text("")
            Text("Macarena sueña con el corte inglés")
            Text("Y se compra los modelos más modernos")
            Text("Le gustaría vivir en Nueva York")
            Text("Y ligar un novio nuevo, ay")
            Text("")
            Text("")
            Text("Macarena sueña con el corte inglés")
            Text("Y se compra los modelos más modernos")
            Text("Le gustaría vivir en Nueva York")
            Text("Y ligar un novio nuevo, ay")
            Text("")
            Text("")
            Text("Dale a tu cuerpo alegría Macarena")
            Text("Que tu cuerpo es pa' darle alegría y cosa buena")
            Text("Dale a tu cuerpo alegría, Macarena")
            Text("Hey Macarena, ay")
            Text("")
            Text("")
            Text("Dale a tu cuerpo alegría Macarena")
            Text("Que tu cuerpo es pa' darle alegría y cosa buena")
            Text("Dale a tu cuerpo alegría, Macarena")
            Text("Hey Macarena, ay")
            
            
        }
    }
}

#Preview {
    ContentView()
}
